rules:
  "no-undef": fa
  indent:
    - 2
    - 2
  quotes:
    - 2
    - double
  linebreak-style:
    - 2
    - unix
  semi:
    - 2
    - always
  "no-undef": 0
  "no-console": 0
globals:
  "$": true
  React: true
  ReactDOM: true
env:
  es6: true
  browser: true
extends: 'eslint:recommended'
ecmaFeatures:
  jsx: true
  experimentalObjectRestSpread: true
plugins:
  - react
