rules:
  indent:
    - 2
    - 2
  "space-before-blocks":
    - 1
    - 
      functions: always
      keywords: always
  quotes:
    - 2
    - double
  linebreak-style:
    - 2
    - unix
  "keyword-spacing":
    - 2
    - before: true
      after: true
  semi:
    - 2
    - always
  "no-undef": 0
  "no-console": 0
globals:
  "$": true
  React: true
  ReactDOM: true
env:
parserOptions:
  ecmaVersion: 6
  ecmaFeatures:
    jsx: true
extends: 'eslint:recommended'
plugins:
  - react
