AllCops:
  Exclude:
    - "db/**/*"
    - "config/**/*"
    - "script/**/*"

Rails:
  Enabled: true

StringLiterals:
  Enabled: false

MultilineOperationIndentation:
  EnforcedStyle: indented

MultilineMethodCallIndentation:
  EnforcedStyle: indented

