AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - "db/**/*"
    - "config/**/*"
    - "script/**/*"

Style/Documentation:
  Enabled: false

Style/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/StringLiterals:
  Enabled: false

Rails:
  Enabled: true
