Rails:
  Enabled: true

StringLiterals:
  Enabled: false

AlignParameters:
  EnforcedStyle: with_fixed_indentation

MutlilineOperationIndentation:
  EnforcedStyle: indented

MultilineMethodCallIndentation:
  EnforcedStyle: indented

